text_extensions: [ 'coffee', 'css', 'erb', 'haml', 'handlebars', 'hb', 'htm', 'html', 'js', 'less', 'markdown', 'md', 'ms', 'mustache', 'php', 'rb', 'sass', 'scss', 'txt', 'xhtml', 'xml' ]
output_dir: output
index_filenames: [ 'index.html' ]
enable_output_diff: false
base_url: 'http://iany.me'

prune:
  auto_prune: false
  exclude: [ '.git', '.hg', '.svn', 'CVS' ]

data_sources:
  -
    type: sprockets
    items_root: /assets
    layouts_root: /
    load_paths: ['assets/js', 'assets/img', 'assets/css']
    precompile: ['vendor.js', 'main.js', 'style.css']
    image_path_prefix: ['/assets/']
    gems:
      - name: 'bootstrap-sass'
        load_paths:
          - 'vendor/assets/javascripts'
          - 'vendor/assets/stylesheets'
          - 'vendor/assets/images'
  -
    type: blog
    items_root: /
    layouts_root: /
    directory: 'content/posts'
  -
    type: ignoreable_filesystem_unified
    items_root: /
    layouts_root: /
    ignore: '^content/posts/'

watcher:
  dirs_to_watch: [ 'content', 'layouts', 'lib', 'assets' ]
  files_to_watch: [ 'config.yaml', 'Rules' ]
  notify_on_compilation_success: true
  notify_on_compilation_failure: true
