text_extensions: [ 'coffee', 'css', 'erb', 'haml', 'handlebars', 'hb', 'htm', 'html', 'js', 'less', 'markdown', 'md', 'ms', 'mustache', 'php', 'rb', 'sass', 'scss', 'txt', 'xhtml', 'xml' ]
output_dir: output
index_filenames: [ 'index.html' ]
enable_output_diff: false
base_url: 'http://iany.me'
sitemap:
  default:
    changefreq: monthly
    priority: 0.6
  index:
    changefreq: daily
    priority: 0.6
  wiki_index:
    changefreq: daily
    priority: 1
  calendar:
    changefreq: daily
    priority: 0.8
  tag:
    changefreq: daily
    priority: 0.9

atom_limit: 10

prune:
  auto_prune: false
  exclude: [ '.git', '.hg', '.svn', 'CVS' ]

data_sources:
  -
    type: sprockets
    items_root: /assets
    layouts_root: /
    load_paths: ['assets/js', 'assets/img', 'assets/css']
    precompile: ['vendor.js', 'main.js', 'style.css', 'MathJax/config/ianyme.js' ]
    image_path_prefix: ['/assets/']
    gems:
      - name: 'bootstrap-sass'
        load_paths:
          - 'vendor/assets/javascripts'
          - 'vendor/assets/stylesheets'
          - 'vendor/assets/images'
  -
    type: blog
    items_root: /
    layouts_root: /
    directory: 'content/posts'
    permlink: ':year/:month/:title'
  -
    type: blog
    name: wiki
    items_root: /wiki
    layouts_root: /
    directory: 'content/wiki'
    source: ':title'
    year_permlink: '/year/:year/'
    permlink: ':title'
    sort: 'updated_at DESC'
    calendar_template: '/_templates/calendar/'
    tag_template: '/_templates/tag/'
  -
    type: ignoreable_filesystem_unified
    items_root: /
    layouts_root: /
    ignore: '^content/(posts|wiki)/'

watcher:
  dirs_to_watch: [ 'content', 'layouts', 'lib', 'assets' ]
  files_to_watch: [ 'config.yaml', 'Rules' ]
  notify_on_compilation_success: true
  notify_on_compilation_failure: true
