source 'http://ruby.taobao.org'

gem 'nanoc', '~>3.4.3'
gem 'mime-types'
gem 'fssm'
gem 'sprockets'
gem 'sprockets-sass'
gem 'bootstrap-sass'
gem 'coffee-script'
gem 'sass'
gem 'erubis'
gem 'redcarpet'
gem 'handlebars'
gem 'pygments.rb'
gem 'nokogiri'
gem 'mini_magick'
gem 'uglifier'
